#!/usr/bin/env python3
"""
Markdown 轉換器
將基於行的分塊結果轉換為 Markdown 格式

轉換規則：
- Level 1, 2, 3, 4, 5, 6... → 數字列表 (1., 2., 3...)
- Level 0 → H2 標題 (##)
- Level -1 → 純文字
- Level -2 → 忽略 (通常是日期)
- Level -3 → 忽略 (通常是 header/footer)
"""

from typing import List, Dict, Optional
from dataclasses import dataclass
from ..detectors.adaptive_hybrid import LineBasedChunk, IntelligentDetectionResult

@dataclass
class MarkdownSection:
    """Markdown 章節"""
    level: int
    content: str
    section_type: str  # "heading", "numbered_list", "plain_text"
    
class MarkdownConverter:
    """Markdown 轉換器"""
    
    def __init__(self):
        self.conversion_stats = {}
    
    def convert_chunks_to_markdown(self, chunks: List[LineBasedChunk], 
                                 include_metadata: bool = False) -> str:
        """
        將分塊結果轉換為 Markdown 格式
        
        Args:
            chunks: 基於行的分塊結果
            include_metadata: 是否包含元數據註釋
            
        Returns:
            Markdown 格式的文本
        """
        markdown_lines = []
        self.conversion_stats = {'h2_count': 0, 'numbered_list_count': 0, 'plain_text_count': 0}
        
        if include_metadata:
            markdown_lines.append("<!-- Generated by L-chunk md_converter -->")
            markdown_lines.append("")
        
        # 按 level 分組聚合內容
        level_groups = self._group_chunks_by_level(chunks)
        
        # 按 level 順序處理（負數在前，0在中間，正數在後）
        sorted_levels = sorted(level_groups.keys())
        
        for level in sorted_levels:
            chunk_group = level_groups[level]
            
            # 忽略 Level -2 (日期) 和 Level -3 (header/footer)
            if level in [-2, -3]:
                continue
            
            markdown_section = self._convert_level_to_markdown(level, chunk_group)
            if markdown_section:
                markdown_lines.extend(markdown_section)
                markdown_lines.append("")  # 添加空行分隔
        
        # 移除最後的空行
        while markdown_lines and markdown_lines[-1] == "":
            markdown_lines.pop()
        
        if include_metadata:
            markdown_lines.append("")
            markdown_lines.append(f"<!-- Conversion Stats: {self.conversion_stats} -->")
        
        return "\n".join(markdown_lines)
    
    def _group_chunks_by_level(self, chunks: List[LineBasedChunk]) -> Dict[int, List[LineBasedChunk]]:
        """按層級分組分塊"""
        level_groups = {}
        
        for chunk in chunks:
            level = chunk.level
            if level not in level_groups:
                level_groups[level] = []
            level_groups[level].append(chunk)
        
        return level_groups
    
    def _convert_level_to_markdown(self, level: int, chunks: List[LineBasedChunk]) -> List[str]:
        """將特定層級的分塊轉換為 Markdown"""
        markdown_lines = []
        
        # 合併同層級的內容
        merged_content = self._merge_chunk_content(chunks)
        
        if not merged_content.strip():
            return []
        
        if level == 0:
            # Level 0 → H2 標題
            markdown_lines.append(f"## {merged_content.strip()}")
            self.conversion_stats['h2_count'] += 1
            
        elif level >= 1:
            # Level 1, 2, 3, 4... → 數字列表
            indent = "  " * (level - 1)  # 每層級縮排 2 個空格
            list_number = 1
            
            for line in merged_content.strip().split('\n'):
                line = line.strip()
                if line:
                    markdown_lines.append(f"{indent}{list_number}. {line}")
                    list_number += 1
            
            self.conversion_stats['numbered_list_count'] += len([l for l in merged_content.strip().split('\n') if l.strip()])
            
        elif level == -1:
            # Level -1 → 純文字
            for line in merged_content.strip().split('\n'):
                line = line.strip()
                if line:
                    markdown_lines.append(line)
            
            self.conversion_stats['plain_text_count'] += len([l for l in merged_content.strip().split('\n') if l.strip()])
        
        return markdown_lines
    
    def _merge_chunk_content(self, chunks: List[LineBasedChunk]) -> str:
        """合併分塊內容"""
        all_content = []
        
        for chunk in chunks:
            # 跳過空內容
            if not chunk.content_lines:
                continue
            
            # 合併內容行
            for line in chunk.content_lines:
                line_text = line.strip()
                if line_text:
                    all_content.append(line_text)
        
        return "\n".join(all_content)
    
    def convert_detection_result_to_markdown(self, detection_result: IntelligentDetectionResult,
                                           include_metadata: bool = True) -> str:
        """
        將完整的檢測結果轉換為 Markdown
        
        Args:
            detection_result: 智能檢測結果
            include_metadata: 是否包含元數據
            
        Returns:
            Markdown 格式的文本
        """
        if not detection_result.line_based_chunks:
            return "<!-- No line-based chunks available for conversion -->"
        
        markdown_content = self.convert_chunks_to_markdown(
            detection_result.line_based_chunks, 
            include_metadata=include_metadata
        )
        
        if include_metadata:
            # 添加檔案資訊
            metadata_header = [
                f"<!-- File: {detection_result.filename} -->",
                f"<!-- Learning Region: {detection_result.learning_region} -->",
                f"<!-- Total Chunks: {len(detection_result.line_based_chunks)} -->",
                "",
                markdown_content
            ]
            return "\n".join(metadata_header)
        
        return markdown_content
    
    def batch_convert_to_markdown(self, detection_results: List[IntelligentDetectionResult],
                                output_dir: Optional[str] = None) -> Dict[str, str]:
        """
        批量轉換多個檢測結果為 Markdown
        
        Args:
            detection_results: 多個檢測結果
            output_dir: 輸出目錄（可選）
            
        Returns:
            檔案名 → Markdown 內容的字典
        """
        converted_files = {}
        
        for result in detection_results:
            if not result.line_based_chunks:
                continue
            
            markdown_content = self.convert_detection_result_to_markdown(result)
            
            # 生成輸出檔名
            base_name = result.filename.replace('.json', '')
            markdown_filename = f"{base_name}_converted.md"
            
            converted_files[markdown_filename] = markdown_content
            
            # 如果指定輸出目錄，則寫入檔案
            if output_dir:
                from pathlib import Path
                output_path = Path(output_dir)
                output_path.mkdir(parents=True, exist_ok=True)
                
                output_file = output_path / markdown_filename
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write(markdown_content)
                
                print(f"✅ 已輸出: {output_file}")
        
        return converted_files

# 使用範例
def demo_md_converter():
    """演示 Markdown 轉換器的使用"""
    from ..detectors.adaptive_hybrid import LineBasedChunk
    
    # 建立測試分塊
    test_chunks = [
        LineBasedChunk(
            level=-3, start_line=0, end_line=2, chunk_type="header",
            content_lines=["法院頭部", "案件編號", "當事人資訊"]
        ),
        LineBasedChunk(
            level=0, start_line=5, end_line=5, chunk_type="main_text",
            content_lines=["主文"]
        ),
        LineBasedChunk(
            level=-1, start_line=6, end_line=8, chunk_type="content",
            content_lines=["原告勝訴", "被告應給付新台幣一百萬元", "訴訟費用由被告負擔"]
        ),
        LineBasedChunk(
            level=0, start_line=10, end_line=10, chunk_type="facts",
            content_lines=["事實"]
        ),
        LineBasedChunk(
            level=1, start_line=11, end_line=12, chunk_type="leveling_symbol",
            content_lines=["一、當事人背景", "二、爭議事項"], leveling_symbol="一、"
        ),
        LineBasedChunk(
            level=2, start_line=13, end_line=14, chunk_type="leveling_symbol", 
            content_lines=["（一）契約簽訂經過", "（二）履行狀況"], leveling_symbol="（一）"
        ),
        LineBasedChunk(
            level=-2, start_line=20, end_line=20, chunk_type="dates",
            content_lines=["中華民國113年10月14日"]
        )
    ]
    
    # 轉換為 Markdown
    converter = MarkdownConverter()
    markdown_result = converter.convert_chunks_to_markdown(test_chunks, include_metadata=True)
    
    print("📝 Markdown 轉換結果:")
    print("=" * 50)
    print(markdown_result)
    print("=" * 50)
    print(f"轉換統計: {converter.conversion_stats}")

if __name__ == "__main__":
    demo_md_converter()